name: lerna

on:
  push:
    branches: [ develop ]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: thanksd/lerna-action@v0.0.16
        with:
          hash: ${{ hashFiles('package-lock.json') }}
