name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: restore npm
        id: restore-npm
        uses: actions/cache@v2
        with: 
          path: ~/.npm 
          key: ${{ runner.os }}-npm-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-

      - name: restore lerna
        id: restore-lerna
        uses: actions/cache@v2
        with:
          path: |
            node_modules
            */*/node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-modules-

      - name: npm install
        if: steps.restore-npm.outputs.cache-hit != 'true'
        run: npm i 

      - name: bootstrap
        if: steps.restore-lerna.outputs.cache-hit != 'true'
        run: npx lerna bootstrap
  
  build:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
  
  test: 
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

  hello:
    runs-on: ubuntu-latest
    steps:
      - name: thanksd hello action
        id: hello
        uses: thanksd/hello-action@v1.2
        with:
          who-to-greet: 'Boo'
      - name: hello output
        run: echo "The time was ${{ steps.hello.outputs.time }}"
        
