name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: restore npm
        id: restore-npm
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-modules-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-modules-

      - name: restore lerna
        id: restore-lerna
        uses: actions/cache@v2
        with:
          path: |
            node_modules
            */*/node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-modules-

      - name: npm install
        if: steps.restore-npm.outputs.cache-hit != 'true'
        run: npm i

      - name: bootstrap
        if: steps.restore-lerna.outputs.cache-hit != 'true'
        run: npx lerna bootstrap

  build:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: restore npm
        id: restore-npm
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-modules-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-modules-

      - name: restore lerna
        id: restore-lerna
        uses: actions/cache@v2
        with:
          path: |
            node_modules
            */*/node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-modules-

      - name: build
        run: npm run build

      - name: save packages
        uses: actions/upload-artifact@v2
        with:
          name: packages
          path: |
            packages/**/dist

  test:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: restore npm
        id: restore-npm
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-modules-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-modules-

      - name: restore lerna
        id: restore-lerna
        uses: actions/cache@v2
        with:
          path: |
            node_modules
            */*/node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-modules-

      - name: test
        run: npm run test

  publish:
    needs:
      - build
      - test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: load packages
        uses: actions/download-artifact@v2
        with:
          name: packages

      - name: restore npm
        id: restore-npm
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-modules-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-modules-

      - name: restore lerna
        id: restore-lerna
        uses: actions/cache@v2
        with:
          path: |
            node_modules
            */*/node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-modules-

      - name: publish
        env:
          NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo $NPM_TOKEN
          git config --global user.email "brianmcmillen@gmail.com"
          git config --global user.name "GitHub Action"
          npm run publish
