name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm run i
      - run: npx lerna bootstrap
  
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
  
  test: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
